---
collections:
  #- ansible.posix
  - containers.podman
  - name: kubernetes.core  # change to redhat.openshift_virtualization is using Ansible Automation Hub
    version: '>=3.0.1'
  - kubevirt.core
  - name: tosin2013.openshift_virt_ansible
    type: git
    source: https://github.com/tosin2013/openshift_virt_ansible.git
    version: main
roles: 
  - linux-system-roles.network
  - linux-system-roles.firewall
  - linux-system-roles.cockpit
